
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartcampus
  labels:
    app: smartcampus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smartcampus
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: smartcampus
    spec:
      containers:
        - name: smartcampus
          image: iamshravani9226/smartcampus:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: APP_VERSION
              value: "1.0.0"
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
